Which of these keywords is used to by the calling function to guard against the exception that is thrown by called function?