What is the output of this program?

lass exception_handling {

      public static void main(String args[]) {

      try {

             throw new NullPointerException ("Hello");

             System.out.print("A");

        }

         catch(ArithmeticException e) {

             System.out.print("B");        	

         }

     }

  }