Which of these exceptions is thrown by remover() method?